package fr.insalyon.creatis.vip.application.server.business;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Lookup;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import fr.insalyon.creatis.vip.application.client.bean.SimulationInput;
import fr.insalyon.creatis.vip.application.server.business.simulation.parser.InputParser;
import fr.insalyon.creatis.vip.application.server.dao.ApplicationInputDAO;
import fr.insalyon.creatis.vip.core.client.VipException;
import fr.insalyon.creatis.vip.core.server.dao.DAOException;
import fr.insalyon.creatis.vip.datamanager.server.business.DataManagerBusiness;

@Service
@Transactional
public class InputBusiness {

    private ApplicationInputDAO applicationInputDAO;
    private DataManagerBusiness dataManagerBusiness;

    @Autowired
    public InputBusiness(ApplicationInputDAO applicationInputDAO, DataManagerBusiness dataManagerBusiness) {
        this.applicationInputDAO = applicationInputDAO;
        this.dataManagerBusiness = dataManagerBusiness;
    }

    @Lookup
    protected InputParser getInputParser() {
        // will be generated by spring to return a new instance each time
        return null;
    }

    public SimulationInput getInputByUserAndName(
            String email, String name, String appName) throws VipException {
        try {
            return applicationInputDAO.getInputByNameUserApp(email, name, appName);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void addSimulationInput(String email, SimulationInput simulationInput)
            throws VipException {
        try {
            applicationInputDAO.addSimulationInput(email, simulationInput);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void updateSimulationInput(
            String email, SimulationInput simulationInput)
            throws VipException {
        try {
            applicationInputDAO.updateSimulationInput(email, simulationInput);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void saveSimulationInputAsExample(SimulationInput simulationInput)
            throws VipException {
        try {
            applicationInputDAO.saveSimulationInputAsExample(simulationInput);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void removeSimulationInput(
            String email, String inputName, String applicationName)
            throws VipException {
        try {
            applicationInputDAO.removeSimulationInput(email, inputName, applicationName);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void removeSimulationInputExample(
            String inputName, String applicationName) throws VipException {
        try {
            applicationInputDAO.removeSimulationInputExample(inputName, applicationName);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public List<SimulationInput> getSimulationInputByUser(String email)
            throws VipException {
        try {
            return applicationInputDAO.getSimulationInputByUser(email);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public List<SimulationInput> getSimulationInputExamples(
            String applicationName) throws VipException {
        try {
            return applicationInputDAO.getSimulationInputExamples(applicationName);
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }
}
