<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.insalyon.creatis</groupId>
        <artifactId>vip</artifactId>
        <version>${revision}${sha1}${changelist}</version>
    </parent>
    <name>VIP-Portal</name>
    <artifactId>vip-portal</artifactId>
    <packaging>war</packaging>

    <url>http://vip.creatis.insa-lyon.fr</url>
    <dependencies>

        <!-- VIP MODULES -->
        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-core</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-docs</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-docs</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

         <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-application-importer</artifactId>
             <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-application-importer</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-datamanager</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-datamanager</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-application</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-application</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-gatelab</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-gatelab</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-publication</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-publication</artifactId>
            <type>jar</type>
            <version>${project.version}</version>
            <classifier>sources</classifier>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-social</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-social</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>

        <dependency>
             <groupId>fr.insalyon.creatis</groupId>
             <artifactId>vip-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-visualization</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>fr.insalyon.creatis</groupId>
          <artifactId>vip-visualization</artifactId>
          <type>jar</type>
          <version>${project.version}</version>
          <classifier>sources</classifier>
          <scope>provided</scope>
        </dependency>
        <!-- END VIP MODULES -->

        <!--dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.23</version>
            <scope>runtime</scope>
        </dependency-->
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.7.14</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2database.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- GWT compilation stuff. Not needed in runtime war so use
         provided scope -->
        
        <dependency>
            <groupId>com.isomorphic.smartgwt.lgpl</groupId>
            <artifactId>smartgwt-lgpl</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-dev</artifactId>
            <scope>provided</scope>
            <exclusions>
                <!-- excluded for conflicts in transitive dependencies in test context  -->
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.googlecode.gflot</groupId>
            <artifactId>gflot</artifactId>
            <version>3.0.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        
        <!-- test dependencies -->
        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-application</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>fr.insalyon.creatis</groupId>
            <artifactId>vip-api</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <!--
            Only needed in the test scope, as the swagger json is generated and copied during a custom test.
            Then the swagger-ui site is static in the webapp.
            To choose the good springdoc version depending of spring version : https://springdoc.org/#what-is-the-compatibility-matrix-of-springdoc-openapi-with-spring-boot
            For spring boot / spring versions link : https://spring.io/projects/generations
        -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.16</version>
            <scope>test</scope>
        </dependency>

        <!-- End test dependencies -->
    </dependencies>

    <build>
        <plugins>
            <!--
                Add a custom surefire:test execution for the single SwaggerDocGenerator class.
                SwaggerDocGenerator is a special JUnit test that generates a swagger json and places it in webapp/api-doc
                As it is not really a test, we disable the test reports.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-api-doc</id>
                        <phase>prepare-package</phase>
                        <configuration>
                            <test>*SwaggerDocGenerator</test>
                            <statelessTestsetReporter>
                                <disable>true</disable>
                            </statelessTestsetReporter>
                            <useFile>false</useFile>
                        </configuration>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>build-frontend</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>bash</executable>
                            <arguments>
                                <argument>${project.basedir}/../scripts/build-frontend.sh</argument>
                            </arguments>
                            <workingDirectory>${project.basedir}/..</workingDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.0.0</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>compile-to-javascript</id>
                        <configuration>
                            <moduleName>fr.insalyon.creatis.vip.portal.Main</moduleName>
                            <jvmArgs>-Xms512m</jvmArgs>
                            <jvmArgs>-Xmx1024m</jvmArgs>
                            <sourceLevel>auto</sourceLevel>
                        </configuration>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.3</version>
                <executions>
                    <execution>
                        <!-- This is the default plugin execution, building the main artefact, the production war.-->
                        <id>default-war</id>
                        <goals><goal>war</goal></goals>
                        <configuration>
                            <packagingExcludes>WEB-INF/lib/*-sources.jar</packagingExcludes>
                            <webResources>
                                <resource>
                                    <directory>${project.basedir}/../frontend/dist</directory>
                                    <targetPath>new_front</targetPath>
                                </resource>
                            </webResources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Just to avoid compiling GWT here-->
            <id>no-gwt</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>net.ltgt.gwt.maven</groupId>
                        <artifactId>gwt-maven-plugin</artifactId>
                        <version>1.0.0</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>compile-to-javascript</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
