package fr.insalyon.creatis.vip.gatelab.server.business;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Lookup;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import fr.insalyon.creatis.vip.application.server.business.ApplicationBusiness;
import fr.insalyon.creatis.vip.core.client.VipException;
import fr.insalyon.creatis.vip.core.models.User;
import fr.insalyon.creatis.vip.core.server.business.EmailBusiness;
import fr.insalyon.creatis.vip.core.server.dao.DAOException;
import fr.insalyon.creatis.vip.core.server.dao.UserDAO;
import fr.insalyon.creatis.vip.gatelab.server.dao.GateLabDAO;

@Service
@Transactional
public class GateLabBusiness {

    private final Logger logger = LoggerFactory.getLogger(getClass());

    private ApplicationBusiness applicationBusiness;
    private UserDAO userDAO;
    private EmailBusiness emailBusiness;

    @Autowired
    public GateLabBusiness(ApplicationBusiness applicationBusiness, UserDAO userDAO, EmailBusiness emailBusiness) {
        this.applicationBusiness = applicationBusiness;
        this.userDAO = userDAO;
        this.emailBusiness = emailBusiness;
    }
    /*
        GateLabInputs is prototyped scoped as a new instance is needed
        at each use because each instance is linked to the parsing of a
        single gatelab simulation. It must be obtained through a lookup method.
    */
    @Lookup
    protected GateLabInputs getGateLabInputs(String workflowID) {
        // will be generated by spring to return a new instance each time
        return null;
    }

    /*
        GetGateLabDAO is prototyped scoped as a new instance is needed
        at each use because each instance is linked to a specific
        simulation/dbPath. It must be obtained through a lookup method
     */
    @Lookup
    protected GateLabDAO getGateLabDAO(String dbPath) {
        // will be generated by spring to return a new instance each time
        return null;
    }

    public List<String[]> getApplications() throws VipException {
        // try {
        //     classDAO.add(new AppClass(
        //             GateLabConstants.GATELAB_CLASS, new ArrayList<String>()));
        // } catch (DAOException ex) {
        //     if (!ex.getMessage().contains("A class named \"" + GateLabConstants.GATELAB_CLASS + "\" already exists")) {
        //         throw new VipException(ex);
        //     }
        // }
        // return applicationBusiness.getApplications(
        //     GateLabConstants.GATELAB_CLASS);
        return new ArrayList<>();
    }

    public Map<String, String> getGatelabWorkflowInputs(String workflowID) throws VipException {

        try {
            GateLabInputs gateinputs = getGateLabInputs(workflowID);
            Map<String, String> inputMap = gateinputs.getWorkflowInputs();

            long nb = getGateLabDAO(workflowID).getNumberParticles();
            inputMap.put("runnedparticles", "" + nb);

            return inputMap;

        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public long getNumberParticles(String workflowID) throws VipException {

        try {
            return getGateLabDAO(workflowID).getNumberParticles();

        } catch (DAOException ex) {
            return 0;
        }
    }

    public void StopWorkflowSimulation(String workflowID) throws VipException {

        try {
            getGateLabDAO(workflowID).StopWorkflowSimulation();

        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }

    public void reportProblem(String email, String message) throws VipException {

        try {
            User user = userDAO.getUser(email);

            String adminsEmailContents = "<html>"
                    + "<head></head>"
                    + "<body>"
                    + "<p>Dear Supporters,</p>"
                    + "<p>The following user tried to submit a GATE-Lab simulation:</p>"
                    + "<p><b>First Name:</b> " + user.getFirstName() + "</p>"
                    + "<p><b>Last Name:</b> " + user.getLastName() + "</p>"
                    + "<p><b>Email:</b> " + user.getEmail() + "</p>"
                    + "<p>&nbsp;</p>"
                    + "<p><b>Error Message:</b></p>"
                    + "<p style=\"background-color: #F6F6F6\">" + message + "</p>"
                    + "<p>&nbsp;</p>"
                    + "<p>Best Regards,</p>"
                    + "<p>VIP Team</p>"
                    + "</body>"
                    + "</html>";

            emailBusiness.sendEmailToAdmins("[VIP Contact] GATE-Lab Error", adminsEmailContents,
                    false, user.getEmail());
        } catch (DAOException ex) {
            throw new VipException(ex);
        }
    }
}
